[features]
resolution = true
skip-lint = false

[programs.devnet]
aeternia_program = "REPLACE_AFTER_ANCHOR_KEYS_SYNC"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/aeternia-program"]
